global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'payment-function'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['192.168.43.69:9080'] #Provide your ip and Do not give localhost as we are running the prometheus in docker
      labels:
        application: payment-function
