server.port: 8084
spring.application.name: "user-service"
server.servlet.context-path: /api
info: User  service

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace