server.port: 8083

info: Order service

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:order
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: ark-01.srvs.cloudkafka.com:9094,ark-02.srvs.cloudkafka.com:9094,ark-03.srvs.cloudkafka.com:9094
          configuration:
            security.protocol: SASL_SSL
            sasl:
              mechanism: SCRAM-SHA-256
              jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="sqcfxdzi" password="***REMOVED***";
      bindings:
        output:
          destination: sqcfxdzi-order


logging.level.org.springframework.cloud.openfeign: trace
